Emiesce/dd2480-assignment1

- DecideTest.java
feat : creating a prototype test file
> Issue#1 : create test case file

- Decide.java
feat : Implementation of the function CMV0 done, the function now takes one paramenter (length1) and compares it to the distant between two consecutive data points from our data set
> Issue#2 : Implement CMV condition 0

- Decide.java
feat : I've implemented the function CMV1 which now takes a parameter (radius1). I've also created a helper function distance(x1,y1,x,2,y2) which calculates distance between (x1,y1) and (x2,y2)
> Issue #3 : Implement CMV condition 1

- Decide.java
feat : implemented the function cmv2, which now takes as parameter the value epsilon.
> Issue #4 : Implement CMV condition 2

- Decide.java
feat : I've implemented the function CMV3 which now takes as parameter area1
> Issue #5 : Implement CMV condition 3

- Decide.java
feat: I've implemented condition 4 in the function CMV4, which now takes as parameter quads and qpts, this implementation is done with two non-nested loops in order to not redo any useless calculations
> #Issue6 : Implement CMV condition 4 

- Decide.java
Implementation done, very straight-forward. The function takes no parameter
> Issue7 : Implement CMV5

- Decide.java
feat : I've implemented the function CMV6, while taking into account the fact that the first and last point might be the same point. This function now takes as parameter dist and n_pts
> Issue #8 : Implement CMV condition 6

- Decide.java
- DecideTest.java
#15
A little bit messy as some other issues had to be partially done to get things to work, after this merge, #18 #19 #21 should be done.
> Issue12 : Implement CMV Condition 10

- Decide.java
- DecideTest.java
> Refactor1 : removed static and made proper unit testing possible

- Decide.java
- DecideTest.java
> fix : issue in test CMV10, and in for iteration limits of CMV10

- DecideTest.java
feat : I've created two unit tests to test the helper functions distance and smallestRadius, each unitTest comes with one assertion
> Issue #24 :  Implement tests for helper function distance and smallestRadius

- Decide.java
- DecideTest.java
I've implemented unitTests, with each time at least one assertTrue and one assertFalse, implementing these tests also enabled me to fix some bugs along the way
> Issue25 : Implement test for CMV 0-6

- Decide.java
- DecideTest.java
I added in functions CMV 0-6 assertions to make sure that parameters had the legal values and that calling the functions with illegal parameters would throw an AssertionError, then I added assertions in the tests of each of these functions to make sure that indeed, calling functions with bad parameters threw assertionErrors
> Issue26 : create assertions in CMV 0-6 to ensure that the conditions for each parameters are met 

- Decide.java
- DecideTest.java
See #40 
Implemented CMV condition 12 along with unit tests for it.
Also upgraded the implementation of CMV condition 10 by adding input checkers and improved its unit test.
> Issue14 implement cmv condition 12

- Decide.java
- DecideTest.java
feat : implemented cmv condition 14 along with its unit tests
Will solve #42
> issue #16 implement cmv condition 14

- Decide.java
- DecideTest.java
feat : implemented cmv condition 8 along with its unit tests
Will close #8
> issue #10 : implement cmv condition 8

- Decide.java
- DecideTest.java
feat: Added CMV11 and also a test for it. Both seem to work correctly.
> Issue/13: Implement CMV condition 11

- Decide.java
- DecideTest.java
feat: added the code for both CMV9 and the test for it. Ran the test successfully.
> Issue/11: Implement CMV condition 9

- Decide.java
- DecideTest.java
feat: added CMV13 and a test for it. Also added a test for the helper function isInsideCircle which is used for CMV13.
> Issue15: Implement CMV condition 13

- Decide.java
- DecideTest.java
feat: Solved the issue by doing what the title says.
> Issue/27: Add assertions to CMV7 and assertThrows tests to testCMV7

- Decide.java
fix: changed place of the assertions of CM7,9,11,13 so they are at the start of the methods.
> Issue/28: Fix so assertions are at the start

- Decide.java
- DecideTest.java
feat: Added FUVCreator as a for loop that checks for whether PUV[i] and PUM[i][j] are false, as well as three test cases from the provided examples
> Issue/19: FUV Creator

- DecideTest.java
feat : added a test case that includes setting all the inputs
close #69
> issue #31 : add a test case for main
